### PR TITLE
nokhte session phase0 fixes

### LINKED ISSUE #58: If there is every a WiFi disconection the other person is able to continue. There is not pausing that is able to happen. It just continues

### PR DESCRIPTION
**Pull request by sonnyvesali**
This includes:
- [ ] reseting the text to index 0 if they leave the app
 - [ ] reseting & pausing if they disconnect from internet

closes #58

### CODE REVIEW

File: packages/client/lib/app/modules/nokhte_session/presentation/mobx/coordinators/phase0/nokhte_session_phase0_widgets_coordinator.dart [hunk 1]
```diff
@@ -63,8 +62,12 @@ abstract class _NokhteSessionPhase0WidgetsCoordinatorBase
   }
 
   smartTextReactor() => reaction((p0) => primarySmartText.currentIndex, (p0) {
-        if (p0 == 2) {
-          Modular.to.navigate('/nokhte_session/phase_one');
+        if (!isConnected) {
```
Comment (soumivesali) [inline packages/client/lib/app/modules/nokhte_session/presentation/mobx/coordinators/phase0/nokhte_session_phase0_widgets_coordinator.dart:65]: Add this everywhere, mmm kay

**Review by soumivesali — APPROVED** [review]
